### ISSUE TITLE
Flash kernel error

### ISSUE THREAD

**Issue by Solaire6** [yarpiin/White-Wolf-Xiaomi-Cupid#1]
Hello, I successfully compiled the kernel through kernel_xiaomi_cupid_build_platform, but after flashing the boot.img, the device has a black screen and can no longer boot to the log page. I'm wondering if there is something wrong with my compilation process?
[build.log](https://github.com/yarpiin/kernel_xiaomi_cupid/files/11781490/build.log)

**Comment by Solaire6** [comment]
Before flashing the kernel, the device was successfully running EvolutionX (https://forum.xda-developers.com/t/rom-13-0-cupid-official-evolution-x-05-29-23.4591391/)

**Comment by yarpiin** [comment]
There is no mention that you should flash boot.img. For flashing kernel Image and dtbo.img you need to use AnyKernel 3. This platform is to build kernel repo for rom building.

**Comment by Solaire6** [comment]
understand, thank you very much.
